independent lib

diff --git a/config b/config
--- a/config
+++ b/config
@@ -1,29 +1,31 @@
-if test -n "$ngx_module_link"; then
-    if test -n "$NDK_SRCS"; then
-        echo "found ngx_devel_kit for ngx_array_var; looks good."
-    else
-        echo "error: ngx_devel_kit is required to build ngx_array_var; please put it before ngx_array_var." 1>&2
-        exit 1
-    fi
-else
-    if echo $HTTP_MODULES | grep " ndk_http_module" > /dev/null; then
-        echo "found ngx_devel_kit for ngx_array_var; looks good."
-    else
-        echo "error: ngx_devel_kit is required to build ngx_array_var; please put it before ngx_array_var." 1>&2
-        exit 1
-    fi
-fi
+#if test -n "$ngx_module_link"; then
+#    if test -n "$NDK_SRCS"; then
+#        echo "found ngx_devel_kit for ngx_array_var; looks good."
+#    else
+#        echo "error: ngx_devel_kit is required to build ngx_array_var; please put it before ngx_array_var." 1>&2
+#        exit 1
+#    fi
+#else
+#    if echo $HTTP_MODULES | grep " ndk_http_module" > /dev/null; then
+#        echo "found ngx_devel_kit for ngx_array_var; looks good."
+#    else
+#        echo "error: ngx_devel_kit is required to build ngx_array_var; please put it before ngx_array_var." 1>&2
+#        exit 1
+#    fi
+#fi
 
 ngx_addon_name=ngx_http_array_var_module
 
 HTTP_ARRAY_VAR_SRCS="                                                       \
                     $ngx_addon_dir/src/ngx_http_array_var_module.c          \
                     $ngx_addon_dir/src/ngx_http_array_var_util.c            \
+                    $ngx_addon_dir/src/ndk.c                                \
                     "
 
 HTTP_ARRAY_VAR_DEPS="                                                       \
                     $ngx_addon_dir/src/ddebug.h                             \
                     $ngx_addon_dir/src/ngx_http_array_var_util.h            \
+                    $ngx_addon_dir/src/ndk.h                                \
                     "
 
 if test -n "$ngx_module_link"; then
